name: fl_scroll_view
description: "fl_scroll_view encapsulates and extends easy_refresh and flutter_staggered_grid_view."
version: 0.0.2
repository: https://github.com/Wayaer/fl_scroll_view

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  easy_refresh: ^3.4.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true