name: fl_scroll_view
description: "fl_scroll_view encapsulates and extends easy_refresh and flutter_staggered_grid_view."
version: 1.0.1
repository: https://github.com/Wayaer/fl_scroll_view

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  easy_refresh: ^3.4.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true